version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  open-pull-requests-limit: 10
  schedule:
    interval: "weekly"
    day: "monday"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
