version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: npm
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      day: "sunday"
