apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eventhub-prod

resources:
  - ../../../zones/bad
  - namespace.yaml

labels:
  - pairs:
      environment: prod
    includeSelectors: false
