apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/part-of: eventhub
    app.kubernetes.io/component: broker
automountServiceAccountToken: false
